Repository Aivle-32bit/32bit-BE, pull requests merged in 2024-07, with the labels that each got.

#23 ✨ Feat: 프론트 배포에 따른 CORS 설정 추가
  src/main/java/com/aivle/bit/global/config/CorsConfig.java
Labels: 기능

#24 ✨ Feat : 마이페이지 비밀번호 변경 기능
  src/main/java/com/aivle/bit/global/exception/ErrorCode.java
  src/main/java/com/aivle/bit/member/controller/MemberController.java
  src/main/java/com/aivle/bit/member/domain/Member.java
  src/main/java/com/aivle/bit/member/dto/request/PasswordForm.java
  src/main/java/com/aivle/bit/member/repository/MemberRepository.java
  src/main/java/com/aivle/bit/member/service/MemberService.java
Labels: 기능

#26 ✨ Feat: 이메일 인증시 중복 이메일 검증 로직 추가
  src/main/java/com/aivle/bit/auth/controller/AuthController.java
  src/main/java/com/aivle/bit/member/repository/MemberRepository.java
  src/main/java/com/aivle/bit/member/service/MemberService.java
  src/test/java/com/aivle/bit/member/service/MemberServiceTest.java
Labels: 기능

#27 🎨 Design: 로고 적용
  src/main/java/com/aivle/bit/global/smtp/HtmlEmailTemplate.java
Labels: 기능

#28 🩹 Refactor : 확인용 코드 제거
  src/main/java/com/aivle/bit/member/domain/Member.java
Labels: 리팩토링

#29 Revert _ 🩹 Refactor : 확인용 코드 제거
  src/main/java/com/aivle/bit/member/domain/Member.java
Labels: 리팩토링

#31 🩹 Refactor : 비밀번호 변경 기능
  src/main/java/com/aivle/bit/auth/controller/AuthController.java
  src/main/java/com/aivle/bit/auth/controller/RefreshTokenController.java
  src/main/java/com/aivle/bit/member/domain/Member.java
Labels: 리팩토링

#33 인증 어노테이션
  src/main/java/com/aivle/bit/auth/controller/AuthController.java
  src/main/java/com/aivle/bit/member/controller/MemberController.java
Labels: 버그

#36 관리자 기능(사용자 관리)
  .gitmessage.txt
  src/main/java/com/aivle/bit/admin/controller/AdminController.java
  src/main/java/com/aivle/bit/admin/dto/request/RejectRequest.java
  src/main/java/com/aivle/bit/admin/dto/response/MemberResponse.java
  src/main/java/com/aivle/bit/admin/service/AdminService.java
  src/main/java/com/aivle/bit/admin/service/SendApproveEmailService.java
  src/main/java/com/aivle/bit/admin/service/SendDormantEmailService.java
  src/main/java/com/aivle/bit/admin/service/SendRejectEmailService.java
  src/main/java/com/aivle/bit/auth/interceptor/AdminInterceptor.java
  src/main/java/com/aivle/bit/auth/service/SignInService.java
  src/main/java/com/aivle/bit/company/domain/CompanyRegistration.java
  src/main/java/com/aivle/bit/company/dto/response/CompanyRegistrationResponse.java
  src/main/java/com/aivle/bit/company/repository/CompanyRegistrationRepository.java
  src/main/java/com/aivle/bit/global/config/AdminArgumentResolver.java
  src/main/java/com/aivle/bit/global/config/AllowUnverifiedUserArgumentResolver.java
  src/main/java/com/aivle/bit/global/config/MemberArgumentResolver.java
  src/main/java/com/aivle/bit/global/exception/ErrorCode.java
  src/main/java/com/aivle/bit/global/smtp/HtmlEmailTemplate.java
  src/main/java/com/aivle/bit/global/smtp/Mail.java
  src/main/java/com/aivle/bit/global/smtp/SesSendApproveEmailService.java
  src/main/java/com/aivle/bit/global/smtp/SesSendDormantEmailService.java
  src/main/java/com/aivle/bit/global/smtp/SesSendRejectEmailService.java
  src/main/java/com/aivle/bit/member/domain/Member.java
  src/main/java/com/aivle/bit/member/repository/MemberRepository.java
  src/main/java/com/aivle/bit/member/service/MemberService.java
  src/test/java/com/aivle/bit/company/service/CompanyRegistrationServiceTest.java
  src/test/java/com/aivle/bit/member/service/MemberServiceTest.java
Labels: 기능

#37 AOP를 이용한 로그인 성공,실패 시 로깅 하도록 적용
  src/main/java/com/aivle/bit/auth/controller/RefreshTokenController.java
  src/main/java/com/aivle/bit/auth/jwt/JwtTokenProvider.java
  src/main/java/com/aivle/bit/auth/logging/aspect/LoginRecordAspect.java
  src/main/java/com/aivle/bit/auth/logging/domain/LoginRecord.java
  src/main/java/com/aivle/bit/auth/logging/repository/LoginRecordRepository.java
  src/main/java/com/aivle/bit/auth/logging/service/LoginRecordService.java
  src/main/java/com/aivle/bit/auth/service/SignInService.java
  src/main/java/com/aivle/bit/global/exception/ErrorCode.java
  src/main/java/com/aivle/bit/member/domain/MemberState.java
Labels: 기능

#38 방문자 수 통계 기능 추가
  src/main/java/com/aivle/bit/BitApplication.java
  src/main/java/com/aivle/bit/admin/controller/AdminController.java
  src/main/java/com/aivle/bit/admin/dto/response/LoginStatisticsResponse.java
  src/main/java/com/aivle/bit/admin/dto/response/MemberStateCountsResponse.java
  src/main/java/com/aivle/bit/admin/dto/response/RegistrationStatisticsResponse.java
  src/main/java/com/aivle/bit/admin/dto/response/VisitCountResponse.java
  src/main/java/com/aivle/bit/admin/dto/response/VisitorStatisticsResponse.java
  src/main/java/com/aivle/bit/admin/service/AdminService.java
  src/main/java/com/aivle/bit/auth/interceptor/VisitorInterceptor.java
  src/main/java/com/aivle/bit/auth/logging/domain/VisitorCount.java
  src/main/java/com/aivle/bit/auth/logging/repository/LoginRecordRepository.java
  src/main/java/com/aivle/bit/auth/logging/repository/VisitorCountRepository.java
  src/main/java/com/aivle/bit/auth/logging/service/LoginRecordService.java
  src/main/java/com/aivle/bit/auth/logging/service/VisitorService.java
  src/main/java/com/aivle/bit/global/config/InterceptorAuthConfig.java
  src/main/java/com/aivle/bit/member/repository/MemberRepository.java
Labels: 기능

#39 🔨 Fix: 오탈자 수정
  src/main/java/com/aivle/bit/admin/dto/response/MemberStateCountsResponse.java
  src/main/java/com/aivle/bit/admin/service/AdminService.java
Labels: 버그

#42 회사 관리 API
  src/main/java/com/aivle/bit/admin/controller/AdminController.java
  src/main/java/com/aivle/bit/admin/controller/AdminStatisticsController.java
  src/main/java/com/aivle/bit/admin/controller/CompanyManageController.java
  src/main/java/com/aivle/bit/admin/controller/MemberManageController.java
  src/main/java/com/aivle/bit/admin/dto/response/CompanyListResponse.java
  src/main/java/com/aivle/bit/admin/service/AdminStatisticsService.java
  src/main/java/com/aivle/bit/admin/service/CompanyManageService.java
  src/main/java/com/aivle/bit/admin/service/MemberManageService.java
  src/main/java/com/aivle/bit/company/domain/Company.java
  src/main/java/com/aivle/bit/company/repository/CompanyRegistrationRepository.java
  src/main/java/com/aivle/bit/company/repository/CompanyRepository.java
  src/main/java/com/aivle/bit/global/exception/ErrorCode.java
  src/main/java/com/aivle/bit/member/domain/Member.java
  src/main/java/com/aivle/bit/member/repository/MemberRepository.java
Labels: 기능

#44 Feature/#43 마이페이지
  src/main/java/com/aivle/bit/company/service/S3Service.java
  src/main/java/com/aivle/bit/global/exception/ErrorCode.java
  src/main/java/com/aivle/bit/member/controller/MemberController.java
  src/main/java/com/aivle/bit/member/domain/Member.java
  src/main/java/com/aivle/bit/member/dto/request/PasswordChangeRequest.java
  src/main/java/com/aivle/bit/member/dto/request/ProfileUpdateRequest.java
  src/main/java/com/aivle/bit/member/dto/response/MemberFindResponse.java
  src/main/java/com/aivle/bit/member/service/MemberService.java
Labels: 기능

#45 ✨ Feat: ip를 가져오는 방식 수정
  src/main/java/com/aivle/bit/auth/logging/aspect/LoginRecordAspect.java
Labels: 기능

#46 메일 전송 기능 추가
  src/main/java/com/aivle/bit/admin/controller/AdminMailController.java
  src/main/java/com/aivle/bit/admin/dto/request/EmailSendAllRequest.java
  src/main/java/com/aivle/bit/admin/dto/request/EmailSendRequest.java
  src/main/java/com/aivle/bit/admin/service/SendAdminMailService.java
  src/main/java/com/aivle/bit/company/service/CompanyRegistrationService.java
  src/main/java/com/aivle/bit/global/config/AllowUnverifiedUserArgumentResolver.java
  src/main/java/com/aivle/bit/global/smtp/HtmlEmailTemplate.java
  src/main/java/com/aivle/bit/global/smtp/Mail.java
  src/main/java/com/aivle/bit/global/smtp/SmtpSendAdminMailService.java
Labels: 기능

#48 Feature/#34문의사항 게시글 기능
  build.gradle
  src/main/java/com/aivle/bit/BitApplication.java
  src/main/java/com/aivle/bit/auth/controller/AuthController.java
  src/main/java/com/aivle/bit/board/controller/BoardController.java
  src/main/java/com/aivle/bit/board/domain/Board.java
  src/main/java/com/aivle/bit/board/dto/request/BoardCreateRequest.java
  src/main/java/com/aivle/bit/board/dto/request/BoardUpdateRequest.java
  src/main/java/com/aivle/bit/board/dto/response/BoardReadResponse.java
  src/main/java/com/aivle/bit/board/repository/BoardRepository.java
  src/main/java/com/aivle/bit/board/service/BoardService.java
  src/main/java/com/aivle/bit/global/domain/BaseTimeEntity.java
  src/main/java/com/aivle/bit/global/exception/ErrorCode.java
  src/main/java/com/aivle/bit/member/domain/Member.java
  src/main/resources/application.yml
Labels: 기능

#51 기업 보고서 도메인 생성
  src/main/java/com/aivle/bit/company/domain/Company.java
  src/main/java/com/aivle/bit/company/domain/CompanyInfo.java
  src/main/java/com/aivle/bit/company/domain/FinancialSummary.java
  src/main/java/com/aivle/bit/company/domain/Metrics.java
  src/main/java/com/aivle/bit/company/domain/MetricsSummary.java
  src/main/java/com/aivle/bit/company/domain/Swot.java
  src/main/java/com/aivle/bit/company/domain/SwotCategory.java
Labels: 기능

#52 ✨ Feat : 공지사항 게시글 기능 구현
  src/main/java/com/aivle/bit/auth/interceptor/AdminInterceptor.java
  src/main/java/com/aivle/bit/auth/interceptor/MemberInterceptor.java
  src/main/java/com/aivle/bit/auth/interceptor/VisitorInterceptor.java
  src/main/java/com/aivle/bit/board/service/BoardService.java
  src/main/java/com/aivle/bit/global/utils/ValidationUtil.java
  src/main/java/com/aivle/bit/member/domain/Member.java
  src/main/java/com/aivle/bit/notice/admin/controller/AdminNoticeController.java
  src/main/java/com/aivle/bit/notice/admin/dto/request/NoticeCreateRequest.java
  src/main/java/com/aivle/bit/notice/admin/dto/request/NoticeUpdateRequest.java
  src/main/java/com/aivle/bit/notice/admin/dto/response/NoticeReadResponse.java
  src/main/java/com/aivle/bit/notice/admin/service/AdminNoticeService.java
  src/main/java/com/aivle/bit/notice/domain/Notice.java
  src/main/java/com/aivle/bit/notice/member/controller/UserNoticeController.java
  src/main/java/com/aivle/bit/notice/member/service/UserNoticeService.java
  src/main/java/com/aivle/bit/notice/repository/NoticeRepository.java
Labels: 기능

#54 회사 보고서 API
  src/main/java/com/aivle/bit/board/service/BoardService.java
  src/main/java/com/aivle/bit/company/controller/CompanyReportController.java
  src/main/java/com/aivle/bit/company/domain/Metrics.java
  src/main/java/com/aivle/bit/company/dto/response/CompanyInfoResponse.java
  src/main/java/com/aivle/bit/company/dto/response/CompanyReportResponse.java
  src/main/java/com/aivle/bit/company/dto/response/MetricsResponse.java
  src/main/java/com/aivle/bit/company/dto/response/MetricsValue.java
  src/main/java/com/aivle/bit/company/dto/response/SwotResponse.java
  src/main/java/com/aivle/bit/company/repository/CompanyInfoRepository.java
  src/main/java/com/aivle/bit/company/repository/CompanyRepository.java
  src/main/java/com/aivle/bit/company/repository/FinancialSummaryRepository.java
  src/main/java/com/aivle/bit/company/repository/MetricsSummaryRepository.java
  src/main/java/com/aivle/bit/company/repository/SwotRepository.java
  src/main/java/com/aivle/bit/company/service/CompanyInfoService.java
  src/main/java/com/aivle/bit/company/service/CompanyReportService.java
  src/main/java/com/aivle/bit/company/service/SwotService.java
  src/main/java/com/aivle/bit/global/exception/ErrorCode.java
  src/main/java/com/aivle/bit/global/utils/HashRandomGenerator.java
  src/main/java/com/aivle/bit/notice/admin/service/AdminNoticeService.java
Labels: 기능

#57 Feature/#55 보고서 페이지 회사 검색 자동완성 기능
  src/main/java/com/aivle/bit/company/controller/CompanySearchController.java
  src/main/java/com/aivle/bit/company/domain/Company.java
  src/main/java/com/aivle/bit/company/dto/response/CompanySearchResponse.java
  src/main/java/com/aivle/bit/company/repository/CompanyRepository.java
  src/main/java/com/aivle/bit/company/service/CompanySearchService.java
  src/main/java/com/aivle/bit/global/exception/ErrorCode.java
  src/main/java/com/aivle/bit/global/exception/GlobalExceptionHandler.java
  src/main/java/com/aivle/bit/global/utils/HangulUtils.java
Labels: 기능

#59 ✨ Feat : 회사 등록 및 삭제 기능
  images/testtttt.jpg
  images/너닿.png
  src/main/java/com/aivle/bit/company/controller/CompanyController.java
  src/main/java/com/aivle/bit/company/domain/Company.java
  src/main/java/com/aivle/bit/company/domain/Swot.java
  src/main/java/com/aivle/bit/company/dto/request/CompanyRequest.java
  src/main/java/com/aivle/bit/company/repository/CompanyRepository.java
  src/main/java/com/aivle/bit/company/service/CompanyReportService.java
  src/main/java/com/aivle/bit/company/service/CompanyService.java
  src/main/java/com/aivle/bit/global/exception/ErrorCode.java
  src/main/java/com/aivle/bit/global/exception/GlobalExceptionHandler.java
  src/main/java/com/aivle/bit/global/exception/ImageSizeExceededException.java
  src/main/resources/application.yml
Labels: 기능
